name: PR Approval

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Auto-approve
    runs-on: self-hosted
    if: github.event.pull_request.user.login == 'Vandy-2498'
    steps:
      - name: Approve Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const result = await github.pulls.createReview({
              owner: Vandy-2498,
              repo: bypass,
              pull_number: 1,
              event: "APPROVE"
            });
            console.log(result.status);
